# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    CC: gcc-8
    CXX: g++-8

  steps:
  - checkout: self
    submodules: true

  - script: |
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      sudo apt-get update -y
      sudo apt-get install g++-8 -y
    displayName: 'Install GNU C++ compiler'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6' 
      addToPath: true 
      architecture: 'x64'

  - script: pip install conan
    displayName: 'Install Conan'

  - script: |
      mkdir out && cd out
      cmake .. -DNNCASE_TARGET=k210 -DCMAKE_BUILD_TYPE=Release
      make -j
      strip bin/ncc
    displayName: 'Build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'out/bin' 
      includeRootFolder: false 
      archiveType: 'tar' # Options: zip, 7z, tar, wim
      tarCompression: 'xz' # Optional. Options: gz, bz2, xz, none
      archiveFile: '$(Build.ArtifactStagingDirectory)/ncc_linux_x64.tar.xz' 
      replaceExistingArchive: true 
      verbose: true
    displayName: 'Publish'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/ncc_linux_x64.tar.xz
      artifact: ncc_linux_x64

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - checkout: self
    submodules: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6' 
      addToPath: true 
      architecture: 'x64'

  - script: pip install conan
    displayName: 'Install Conan'

  - script: |
      md out && cd out
      cmake .. -G "Visual Studio 16 2019" -A x64 -DNNCASE_TARGET=k210 -DCMAKE_BUILD_TYPE=Release
    displayName: 'Build'

  - task: MSBuild@1
    inputs:
      solution: 'out/nncase.sln'
      msbuildArchitecture: 'x64'
      configuration: 'Release'
      msbuildArguments: '-m'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'out/bin' 
      includeRootFolder: false 
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      archiveFile: '$(Build.ArtifactStagingDirectory)/ncc_win_x64.zip' 
      replaceExistingArchive: true 
      verbose: true
    displayName: 'Publish'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/ncc_win_x64.zip
      artifact: ncc_win_x64